# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YogiYoCloneIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YogiYoCloneIOS
    pod 'Alamofire', '~> 5.2'
    pod 'Kingfisher', '~> 5.0'
    pod 'SnapKit', '~> 5.0.0'
    pod 'Cosmos'
    pod 'KakaoSDK'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/Analytics'
end
